import {
WavesLadder,
Sparkles,
Palmtree,
Waves,
Wine,
Bath,
BookOpen,
Shirt,
Martini,
ShowerHead,
WindArrowDown,
CigaretteOff,
UtensilsCrossed,
Dumbbell,
Wifi,
Trees,
Clock,
Blocks,
BookOpenCheck,
BatteryPlus,
BadgeCent,
BottleWine,
SportShoe,
Coffee,
TicketsPlane,
Utensils,
BookA,
HelpCircle,
} from "lucide-react";

export const facilityIconMap: Record<string, React.ElementType> = {
"Swimming pool": WavesLadder,
"Spa & Wellness Amenities": Sparkles,
"Private beach": Palmtree,
"Infinity pool": Waves,
"Bar": Wine,
"Jacuzzi": Bath,
"Library Lounge": BookOpen,
"Laundry & ironing services": Shirt,
"Welcome Drinks": Martini,
"Sauna and Steam": ShowerHead,
"Air conditioning" : WindArrowDown,
"Smoke-free property": CigaretteOff,
"On-site gourmet restaurant": UtensilsCrossed,
"Restaurant": UtensilsCrossed,
"Bathtub": Bath,
"Gym": Dumbbell,
"Free Wi-Fi": Wifi,
"24-hour reception": Clock,
"Garden": Trees,
"Kid Equipment": Blocks,
"Interconnecting rooms avail...": BookOpenCheck,
"Health club": BatteryPlus,
"Foreign exchange": BadgeCent,
"Poolside Bar and Grill": BottleWine,
"Skiing": SportShoe,
"Outdoor Activities": SportShoe,
"Themed Nights and Activities": Coffee,
"Travel Desk": TicketsPlane,
"Breakfast": Utensils,
"English": BookA,
};
export const getFacilityIcon = (facilityName: string) => {
    if (!facilityName) return HelpCircle;
    return facilityIconMap[facilityName] || HelpCircle
}